### ISSUE TITLE
[Feature] Add "Timer and Best Time Tracker"

### ISSUE THREAD

**Issue by arunimaChintu** [Dev-tanay/Rubik-Cube#374]
### Description

Timer and Best Time Tracker

### Checklist

- [X] I have checked the existing [issues](https://github.com/Dev-tanay/Rubik-Cube/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
